declare module '@mui/material/styles' {
  interface Palette {
    onPrimary: Palette['primary']
    primaryContainer: Palette['primary']
    onPrimaryContainer: Palette['primary']
    onSecondary: Palette['primary']
    secondaryContainer: Palette['primary']
    onSecondaryContainer: Palette['primary']
    tertiary: Palette['primary']
    onTertiary: Palette['primary']
    tertiaryContainer: Palette['primary']
    onTertiaryContainer: Palette['primary']
    errorContainer: Palette['primary']
    onError: Palette['primary']
    onErrorContainer: Palette['primary']
    surface: Palette['primary']
    onSurface: Palette['primary']
    surfaceVariant: Palette['primary']
    onSurfaceVariant: Palette['primary']
    outline: Palette['primary']
    inverseOnSurface: Palette['primary']
    inverseSurface: Palette['primary']
  }
  interface PaletteOptions {
    onPrimary: PaletteOptions['primary']
    primaryContainer: PaletteOptions['primary']
    onPrimaryContainer: PaletteOptions['primary']
    onSecondary: PaletteOptions['primary']
    secondaryContainer: PaletteOptions['primary']
    onSecondaryContainer: PaletteOptions['primary']
    tertiary: PaletteOptions['primary']
    onTertiary: PaletteOptions['primary']
    tertiaryContainer: PaletteOptions['primary']
    onTertiaryContainer: PaletteOptions['primary']
    errorContainer: PaletteOptions['primary']
    onError: PaletteOptions['primary']
    onErrorContainer: PaletteOptions['primary']
    surface: PaletteOptions['primary']
    onSurface: PaletteOptions['primary']
    surfaceVariant: PaletteOptions['primary']
    onSurfaceVariant: PaletteOptions['primary']
    outline: PaletteOptions['primary']
    inverseOnSurface: PaletteOptions['primary']
    inverseSurface: PaletteOptions['primary']
  }
}

export default {
  RedSandDunes: {
    name: 'RedSandDunes',
    palette: {
      light: {
        error: { main: '#ba1b1b' },
        errorContainer: { main: '#ffdad4' },
        onError: { main: '#ffffff' },
        onErrorContainer: { main: '#410001' },
        primary: { main: '#9c4234' },
        primaryContainer: { main: '#ffdad2' },
        onPrimary: { main: '#ffffff' },
        onPrimaryContainer: { main: '#400100' },
        secondary: { main: '#775751' },
        secondaryContainer: { main: '#ffdad3' },
        onSecondary: { main: '#ffffff' },
        onSecondaryContainer: { main: '#2d1511' },
        tertiary: { main: '#6f5c2e' },
        tertiaryContainer: { main: '#fbe0a6' },
        onTertiary: { main: '#ffffff' },
        onTertiaryContainer: { main: '#261a00' },
        surface: { main: '#fcfcfc' },
        surfaceVariant: { main: '#f5deda' },
        onSurface: { main: '#201a19' },
        onSurfaceVariant: { main: '#534341' },
        inverseSurface: { main: '#362f2e' },
        inverseOnSurface: { main: '#fbeeeb' },
        outline: { main: '#857370' },
      },
      dark: {
        error: { main: '#ffb4a9' },
        errorContainer: { main: '#930006' },
        onError: { main: '#680003' },
        onErrorContainer: { main: '#ffdad4' },
        primary: { main: '#ffb4a5' },
        primaryContainer: { main: '#ffdad2' },
        onPrimary: { main: '#5e150c' },
        onPrimaryContainer: { main: '#7d2b1f' },
        secondary: { main: '#e7bdb5' },
        secondaryContainer: { main: '#5d3f3a' },
        onSecondary: { main: '#442924' },
        onSecondaryContainer: { main: '#ffdad3' },
        tertiary: { main: '#dec48c' },
        tertiaryContainer: { main: '#564519' },
        onTertiary: { main: '#3d2e04' },
        onTertiaryContainer: { main: '#fbe0a6' },
        surface: { main: '#201a19' },
        surfaceVariant: { main: '#534341' },
        onSurface: { main: '#ede0de' },
        onSurfaceVariant: { main: '#d8c2be' },
        inverseSurface: { main: '#ede0de' },
        inverseOnSurface: { main: '#fbeeeb' },
        outline: { main: '#a08c89' },
      },
    },
  },
  GreenMountainTop: {
    name: 'GreenMountainTop',
    palette: {
      light: {
        primary: { main: '#006c47' },
        onPrimary: { main: '#ffffff' },
        primaryContainer: { main: '#8cf8c3' },
        onPrimaryContainer: { main: '#002112' },
        secondary: { main: '#4d6356' },
        onSecondary: { main: '#ffffff' },
        secondaryContainer: { main: '#d0e8d8' },
        onSecondaryContainer: { main: '#0a2015' },
        tertiary: { main: '#3d6473' },
        onTertiary: { main: '#ffffff' },
        tertiaryContainer: { main: '#c0e9fb' },
        onTertiaryContainer: { main: '#001f29' },
        error: { main: '#ba1b1b' },
        errorContainer: { main: '#ffdad4' },
        onError: { main: '#ffffff' },
        onErrorContainer: { main: '#410001' },
        surface: { main: '#fbfdf8' },
        onSurface: { main: '#191c1a' },
        surfaceVariant: { main: '#dce5dd' },
        onSurfaceVariant: { main: '#404943' },
        outline: { main: '#707972' },
        inverseOnSurface: { main: '#f0f1ed' },
        inverseSurface: { main: '#2d312e' },
      },
      dark: {
        primary: { main: '#70dba8' },
        onPrimary: { main: '#003822' },
        primaryContainer: { main: '#005235' },
        onPrimaryContainer: { main: '#8cf8c3' },
        secondary: { main: '#b3ccbc' },
        onSecondary: { main: '#20352a' },
        secondaryContainer: { main: '#364b3f' },
        onSecondaryContainer: { main: '#d0e8d8' },
        tertiary: { main: '#a5cdde' },
        onTertiary: { main: '#063543' },
        tertiaryContainer: { main: '#234c5a' },
        onTertiaryContainer: { main: '#c0e9fb' },
        error: { main: '#ffb4a9' },
        errorContainer: { main: '#930006' },
        onError: { main: '#680003' },
        onErrorContainer: { main: '#ffdad4' },
        surface: { main: '#191c1a' },
        onSurface: { main: '#e1e3df' },
        surfaceVariant: { main: '#404943' },
        onSurfaceVariant: { main: '#bfc9c1' },
        outline: { main: '#8a938c' },
        inverseOnSurface: { main: '#191c1a' },
        inverseSurface: { main: '#e1e3df' },
      },
    },
  },
  OrangeDesert: {
    name: 'OrangeDesert',
    palette: {
      light: {
        primary: { main: '#944a02' },
        onPrimary: { main: '#ffffff' },
        primaryContainer: { main: '#ffdcc4' },
        onPrimaryContainer: { main: '#301400' },
        secondary: { main: '#755845' },
        onSecondary: { main: '#ffffff' },
        secondaryContainer: { main: '#ffdcc4' },
        onSecondaryContainer: { main: '#2b1708' },
        tertiary: { main: '#5f6135' },
        onTertiary: { main: '#ffffff' },
        tertiaryContainer: { main: '#e5e6ae' },
        onTertiaryContainer: { main: '#1b1d00' },
        error: { main: '#ba1b1b' },
        errorContainer: { main: '#ffdad4' },
        onError: { main: '#ffffff' },
        onErrorContainer: { main: '#410001' },
        surface: { main: '#fcfcfc' },
        onSurface: { main: '#201a17' },
        surfaceVariant: { main: '#f4dfd3' },
        onSurfaceVariant: { main: '#52443b' },
        outline: { main: '#85746a' },
        inverseOnSurface: { main: '#faeee8' },
        inverseSurface: { main: '#362f2b' },
      },
      dark: {
        primary: { main: '#ffb683' },
        onPrimary: { main: '#502400' },
        primaryContainer: { main: '#723600' },
        onPrimaryContainer: { main: '#ffdcc4' },
        secondary: { main: '#e4bfa8' },
        onSecondary: { main: '#422b1b' },
        secondaryContainer: { main: '#5b412f' },
        onSecondaryContainer: { main: '#ffdcc4' },
        tertiary: { main: '#c8ca94' },
        onTertiary: { main: '#31320b' },
        tertiaryContainer: { main: '#47491f' },
        onTertiaryContainer: { main: '#e5e6ae' },
        error: { main: '#ffb4a9' },
        errorContainer: { main: '#930006' },
        onError: { main: '#680003' },
        onErrorContainer: { main: '#ffdad4' },
        surface: { main: '#201a17' },
        onSurface: { main: '#ece0da' },
        surfaceVariant: { main: '#52443b' },
        onSurfaceVariant: { main: '#d7c3b7' },
        outline: { main: '#9f8d83' },
        inverseOnSurface: { main: '#201a17' },
        inverseSurface: { main: '#ece0da' },
      },
    },
  },
  BlueMountains: {
    name: 'BlueMountains',
    palette: {
      light: {
        primary: { main: '#005ac5' },
        onPrimary: { main: '#ffffff' },
        primaryContainer: { main: '#d6e2ff' },
        onPrimaryContainer: { main: '#001a43' },
        secondary: { main: '#575e71' },
        onSecondary: { main: '#ffffff' },
        secondaryContainer: { main: '#dae2f9' },
        onSecondaryContainer: { main: '#141b2c' },
        tertiary: { main: '#715574' },
        onTertiary: { main: '#ffffff' },
        tertiaryContainer: { main: '#fbd7fb' },
        onTertiaryContainer: { main: '#29132d' },
        error: { main: '#ba1b1b' },
        errorContainer: { main: '#ffdad4' },
        onError: { main: '#ffffff' },
        onErrorContainer: { main: '#410001' },
        surface: { main: '#fdfbff' },
        onSurface: { main: '#1b1b1e' },
        surfaceVariant: { main: '#e1e2ec' },
        onSurfaceVariant: { main: '#44474f' },
        outline: { main: '#74777f' },
        inverseOnSurface: { main: '#f2f0f4' },
        inverseSurface: { main: '#2f3033' },
      },
      dark: {
        primary: { main: '#acc7ff' },
        onPrimary: { main: '#002e6c' },
        primaryContainer: { main: '#004397' },
        onPrimaryContainer: { main: '#d6e2ff' },
        secondary: { main: '#bfc6dc' },
        onSecondary: { main: '#283041' },
        secondaryContainer: { main: '#3f4759' },
        onSecondaryContainer: { main: '#dae2f9' },
        tertiary: { main: '#debbdf' },
        onTertiary: { main: '#402843' },
        tertiaryContainer: { main: '#583e5b' },
        onTertiaryContainer: { main: '#fbd7fb' },
        error: { main: '#ffb4a9' },
        errorContainer: { main: '#930006' },
        onError: { main: '#680003' },
        onErrorContainer: { main: '#ffdad4' },
        surface: { main: '#1b1b1e' },
        onSurface: { main: '#e4e2e6' },
        surfaceVariant: { main: '#44474f' },
        onSurfaceVariant: { main: '#c4c6d0' },
        outline: { main: '#8e9099' },
        inverseOnSurface: { main: '#1b1b1e' },
        inverseSurface: { main: '#e4e2e6' },
      },
    },
  },
  GreenRockyMountains: {
    name: 'GreenRockyMountains',
    palette: {
      light: {
        primary: { main: '#476810' },
        onPrimary: { main: '#ffffff' },
        primaryContainer: { main: '#c6f089' },
        onPrimaryContainer: { main: '#102000' },
        secondary: { main: '#586249' },
        onSecondary: { main: '#ffffff' },
        secondaryContainer: { main: '#dce6c7' },
        onSecondaryContainer: { main: '#161e0a' },
        tertiary: { main: '#396662' },
        onTertiary: { main: '#ffffff' },
        tertiaryContainer: { main: '#bbece6' },
        onTertiaryContainer: { main: '#00201e' },
        error: { main: '#ba1b1b' },
        errorContainer: { main: '#ffdad4' },
        onError: { main: '#ffffff' },
        onErrorContainer: { main: '#410001' },
        surface: { main: '#fdfcf4' },
        onSurface: { main: '#1b1c18' },
        surfaceVariant: { main: '#e1e4d5' },
        onSurfaceVariant: { main: '#44483d' },
        outline: { main: '#75786c' },
        inverseOnSurface: { main: '#f2f1e9' },
        inverseSurface: { main: '#30312c' },
      },
      dark: {
        primary: { main: '#abd371' },
        onPrimary: { main: '#203600' },
        primaryContainer: { main: '#304f00' },
        onPrimaryContainer: { main: '#c6f089' },
        secondary: { main: '#c0caac' },
        onSecondary: { main: '#2b331e' },
        secondaryContainer: { main: '#414a33' },
        onSecondaryContainer: { main: '#dce6c7' },
        tertiary: { main: '#a0cfca' },
        onTertiary: { main: '#013734' },
        tertiaryContainer: { main: '#1f4e4a' },
        onTertiaryContainer: { main: '#bbece6' },
        error: { main: '#ffb4a9' },
        errorContainer: { main: '#930006' },
        onError: { main: '#680003' },
        onErrorContainer: { main: '#ffdad4' },
        surface: { main: '#1b1c18' },
        onSurface: { main: '#e4e3dc' },
        surfaceVariant: { main: '#44483d' },
        onSurfaceVariant: { main: '#c5c8b9' },
        outline: { main: '#8f9285' },
        inverseOnSurface: { main: '#1b1c18' },
        inverseSurface: { main: '#e4e3dc' },
      },
    },
  },
  PurpleDress: {
    name: 'PurpleDress',
    palette: {
      light: {
        primary: { main: '#534fc0' },
        onPrimary: { main: '#ffffff' },
        primaryContainer: { main: '#e2dfff' },
        onPrimaryContainer: { main: '#0f0069' },
        secondary: { main: '#5e5c71' },
        onSecondary: { main: '#ffffff' },
        secondaryContainer: { main: '#e3e0f9' },
        onSecondaryContainer: { main: '#1a1a2c' },
        tertiary: { main: '#7a5368' },
        onTertiary: { main: '#ffffff' },
        tertiaryContainer: { main: '#ffd8ea' },
        onTertiaryContainer: { main: '#2f1123' },
        error: { main: '#ba1a1a' },
        onError: { main: '#ffffff' },
        errorContainer: { main: '#ffdad6' },
        onErrorContainer: { main: '#410002' },
        surface: { main: '#fffbff' },
        onSurface: { main: '#1c1b1f' },
        surfaceVariant: { main: '#e4e1ec' },
        onSurfaceVariant: { main: '#47464f' },
        outline: { main: '#787680' },
        outlineVariant: { main: '#c8c5d0' },
        shadow: { main: '#000000' },
        scrim: { main: '#000000' },
        inverseSurface: { main: '#313034' },
        inverseOnSurface: { main: '#f3eff4' },
        inversePrimary: { main: '#c3c0ff' },
      },
      dark: {
        primary: { main: '#c3c0ff' },
        onPrimary: { main: '#221791' },
        primaryContainer: { main: '#3b35a7' },
        onPrimaryContainer: { main: '#e2dfff' },
        secondary: { main: '#c7c4dd' },
        onSecondary: { main: '#2f2e42' },
        secondaryContainer: { main: '#464559' },
        onSecondaryContainer: { main: '#e3e0f9' },
        tertiary: { main: '#eab9d1' },
        onTertiary: { main: '#472639' },
        tertiaryContainer: { main: '#603c50' },
        onTertiaryContainer: { main: '#ffd8ea' },
        error: { main: '#ffb4ab' },
        onError: { main: '#690005' },
        errorContainer: { main: '#93000a' },
        onErrorContainer: { main: '#ffb4ab' },
        surface: { main: '#1c1b1f' },
        onSurface: { main: '#e5e1e6' },
        surfaceVariant: { main: '#47464f' },
        onSurfaceVariant: { main: '#c8c5d0' },
        outline: { main: '#928f9a' },
        outlineVariant: { main: '#47464f' },
        shadow: { main: '#000000' },
        scrim: { main: '#000000' },
        inverseSurface: { main: '#e5e1e6' },
        inverseOnSurface: { main: '#313034' },
        inversePrimary: { main: '#534fc0' },
      },
    },
  },
}
