export default {
  one: {
    name: 'one',
    palette: {
      light: {
        error: '#ba1b1b',
        errorContainer: { base: '#ffdad4' },
        onError: { base: '#ffffff' },
        onErrorContainer: { base: '#410001' },
        primary: '#9c4234',
        primaryContainer: { base: '#ffdad2' },
        onPrimary: { base: '#ffffff' },
        onPrimaryContainer: { base: '#400100' },
        secondary: '#775751',
        secondaryContainer: { base: '#ffdad3' },
        onSecondary: { base: '#ffffff' },
        onSecondaryContainer: { base: '#2d1511' },
        tertiary: '#6f5c2e',
        tertiaryContainer: { base: '#fbe0a6' },
        onTertiary: { base: '#ffffff' },
        onTertiaryContainer: { base: '#261a00' },
        background: { base: '#fcfcfc' },
        onBackground: { base: '#201a19' },
        surface: { base: '#fcfcfc' },
        surfaceVariant: { base: '#f5deda' },
        onSurface: { base: '#201a19' },
        onSurfaceVariant: { base: '#534341' },
        inverseSurface: { base: '#362f2e' },
        inverseOnSurface: { base: '#fbeeeb' },
        outline: { base: '#857370' },
      },
      dark: {
        error: '#ffb4a9',
        errorContainer: { base: '#930006' },
        onError: { base: '#680003' },
        onErrorContainer: { base: '#ffdad4' },
        primary: '#ffb4a5',
        primaryContainer: { base: '#ffdad2' },
        onPrimary: { base: '#5e150c' },
        onPrimaryContainer: { base: '#7d2b1f' },
        secondary: '#e7bdb5',
        secondaryContainer: { base: '#5d3f3a' },
        onSecondary: { base: '#442924' },
        onSecondaryContainer: { base: '#ffdad3' },
        tertiary: '#dec48c',
        tertiaryContainer: { base: '#564519' },
        onTertiary: { base: '#3d2e04' },
        onTertiaryContainer: { base: '#fbe0a6' },
        background: { base: '#201a19' },
        onBackground: { base: '#ede0de' },
        surface: { base: '#201a19' },
        surfaceVariant: { base: '#534341' },
        onSurface: { base: '#ede0de' },
        onSurfaceVariant: { base: '#d8c2be' },
        inverseSurface: { base: '#ede0de' },
        inverseOnSurface: { base: '#fbeeeb' },
        outline: { base: '#a08c89' },
      },
    },
  },
  two: {
    name: 'two',
    palette: {
      light: {
        primary: '#006c47',
        onPrimary: { base: '#ffffff' },
        primaryContainer: { base: '#8cf8c3' },
        onPrimaryContainer: { base: '#002112' },
        secondary: '#4d6356',
        onSecondary: { base: '#ffffff' },
        secondaryContainer: { base: '#d0e8d8' },
        onSecondaryContainer: { base: '#0a2015' },
        tertiary: '#3d6473',
        onTertiary: { base: '#ffffff' },
        tertiaryContainer: { base: '#c0e9fb' },
        onTertiaryContainer: { base: '#001f29' },
        error: '#ba1b1b',
        errorContainer: { base: '#ffdad4' },
        onError: { base: '#ffffff' },
        onErrorContainer: { base: '#410001' },
        background: { base: '#fbfdf8' },
        onBackground: { base: '#191c1a' },
        surface: { base: '#fbfdf8' },
        onSurface: { base: '#191c1a' },
        surfaceVariant: { base: '#dce5dd' },
        onSurfaceVariant: { base: '#404943' },
        outline: { base: '#707972' },
        inverseOnSurface: { base: '#f0f1ed' },
        inverseSurface: { base: '#2d312e' },
      },
      dark: {
        primary: '#70dba8',
        onPrimary: { base: '#003822' },
        primaryContainer: { base: '#005235' },
        onPrimaryContainer: { base: '#8cf8c3' },
        secondary: '#b3ccbc',
        onSecondary: { base: '#20352a' },
        secondaryContainer: { base: '#364b3f' },
        onSecondaryContainer: { base: '#d0e8d8' },
        tertiary: '#a5cdde',
        onTertiary: { base: '#063543' },
        tertiaryContainer: { base: '#234c5a' },
        onTertiaryContainer: { base: '#c0e9fb' },
        error: '#ffb4a9',
        errorContainer: { base: '#930006' },
        onError: { base: '#680003' },
        onErrorContainer: { base: '#ffdad4' },
        background: { base: '#191c1a' },
        onBackground: { base: '#e1e3df' },
        surface: { base: '#191c1a' },
        onSurface: { base: '#e1e3df' },
        surfaceVariant: { base: '#404943' },
        onSurfaceVariant: { base: '#bfc9c1' },
        outline: { base: '#8a938c' },
        inverseOnSurface: { base: '#191c1a' },
        inverseSurface: { base: '#e1e3df' },
      },
    },
  },
  three: {
    name: 'three',
    palette: {
      light: {
        primary: '#944a02',
        onPrimary: { base: '#ffffff' },
        primaryContainer: { base: '#ffdcc4' },
        onPrimaryContainer: { base: '#301400' },
        secondary: '#755845',
        onSecondary: { base: '#ffffff' },
        secondaryContainer: { base: '#ffdcc4' },
        onSecondaryContainer: { base: '#2b1708' },
        tertiary: '#5f6135',
        onTertiary: { base: '#ffffff' },
        tertiaryContainer: { base: '#e5e6ae' },
        onTertiaryContainer: { base: '#1b1d00' },
        error: '#ba1b1b',
        errorContainer: { base: '#ffdad4' },
        onError: { base: '#ffffff' },
        onErrorContainer: { base: '#410001' },
        background: { base: '#fcfcfc' },
        onBackground: { base: '#201a17' },
        surface: { base: '#fcfcfc' },
        onSurface: { base: '#201a17' },
        surfaceVariant: { base: '#f4dfd3' },
        onSurfaceVariant: { base: '#52443b' },
        outline: { base: '#85746a' },
        inverseOnSurface: { base: '#faeee8' },
        inverseSurface: { base: '#362f2b' },
      },
      dark: {
        primary: '#ffb683',
        onPrimary: { base: '#502400' },
        primaryContainer: { base: '#723600' },
        onPrimaryContainer: { base: '#ffdcc4' },
        secondary: '#e4bfa8',
        onSecondary: { base: '#422b1b' },
        secondaryContainer: { base: '#5b412f' },
        onSecondaryContainer: { base: '#ffdcc4' },
        tertiary: '#c8ca94',
        onTertiary: { base: '#31320b' },
        tertiaryContainer: { base: '#47491f' },
        onTertiaryContainer: { base: '#e5e6ae' },
        error: '#ffb4a9',
        errorContainer: { base: '#930006' },
        onError: { base: '#680003' },
        onErrorContainer: { base: '#ffdad4' },
        background: { base: '#201a17' },
        onBackground: { base: '#ece0da' },
        surface: { base: '#201a17' },
        onSurface: { base: '#ece0da' },
        surfaceVariant: { base: '#52443b' },
        onSurfaceVariant: { base: '#d7c3b7' },
        outline: { base: '#9f8d83' },
        inverseOnSurface: { base: '#201a17' },
        inverseSurface: { base: '#ece0da' },
      },
    },
  },
  four: {
    name: 'four',
    palette: {
      light: {
        primary: '#005ac5',
        onPrimary: { base: '#ffffff' },
        primaryContainer: { base: '#d6e2ff' },
        onPrimaryContainer: { base: '#001a43' },
        secondary: '#575e71',
        onSecondary: { base: '#ffffff' },
        secondaryContainer: { base: '#dae2f9' },
        onSecondaryContainer: { base: '#141b2c' },
        tertiary: '#715574',
        onTertiary: { base: '#ffffff' },
        tertiaryContainer: { base: '#fbd7fb' },
        onTertiaryContainer: { base: '#29132d' },
        error: '#ba1b1b',
        errorContainer: { base: '#ffdad4' },
        onError: { base: '#ffffff' },
        onErrorContainer: { base: '#410001' },
        background: { base: '#fdfbff' },
        onBackground: { base: '#1b1b1e' },
        surface: { base: '#fdfbff' },
        onSurface: { base: '#1b1b1e' },
        surfaceVariant: { base: '#e1e2ec' },
        onSurfaceVariant: { base: '#44474f' },
        outline: { base: '#74777f' },
        inverseOnSurface: { base: '#f2f0f4' },
        inverseSurface: { base: '#2f3033' },
      },
      dark: {
        primary: '#acc7ff',
        onPrimary: { base: '#002e6c' },
        primaryContainer: { base: '#004397' },
        onPrimaryContainer: { base: '#d6e2ff' },
        secondary: '#bfc6dc',
        onSecondary: { base: '#283041' },
        secondaryContainer: { base: '#3f4759' },
        onSecondaryContainer: { base: '#dae2f9' },
        tertiary: '#debbdf',
        onTertiary: { base: '#402843' },
        tertiaryContainer: { base: '#583e5b' },
        onTertiaryContainer: { base: '#fbd7fb' },
        error: '#ffb4a9',
        errorContainer: { base: '#930006' },
        onError: { base: '#680003' },
        onErrorContainer: { base: '#ffdad4' },
        background: { base: '#1b1b1e' },
        onBackground: { base: '#e4e2e6' },
        surface: { base: '#1b1b1e' },
        onSurface: { base: '#e4e2e6' },
        surfaceVariant: { base: '#44474f' },
        onSurfaceVariant: { base: '#c4c6d0' },
        outline: { base: '#8e9099' },
        inverseOnSurface: { base: '#1b1b1e' },
        inverseSurface: { base: '#e4e2e6' },
      },
    },
  },
  five: {
    name: 'five',
    palette: {
      light: {
        primary: '#476810',
        onPrimary: { base: '#ffffff' },
        primaryContainer: { base: '#c6f089' },
        onPrimaryContainer: { base: '#102000' },
        secondary: '#586249',
        onSecondary: { base: '#ffffff' },
        secondaryContainer: { base: '#dce6c7' },
        onSecondaryContainer: { base: '#161e0a' },
        tertiary: '#396662',
        onTertiary: { base: '#ffffff' },
        tertiaryContainer: { base: '#bbece6' },
        onTertiaryContainer: { base: '#00201e' },
        error: '#ba1b1b',
        errorContainer: { base: '#ffdad4' },
        onError: { base: '#ffffff' },
        onErrorContainer: { base: '#410001' },
        background: { base: '#fdfcf4' },
        onBackground: { base: '#1b1c18' },
        surface: { base: '#fdfcf4' },
        onSurface: { base: '#1b1c18' },
        surfaceVariant: { base: '#e1e4d5' },
        onSurfaceVariant: { base: '#44483d' },
        outline: { base: '#75786c' },
        inverseOnSurface: { base: '#f2f1e9' },
        inverseSurface: { base: '#30312c' },
      },
      dark: {
        primary: '#abd371',
        onPrimary: { base: '#203600' },
        primaryContainer: { base: '#304f00' },
        onPrimaryContainer: { base: '#c6f089' },
        secondary: '#c0caac',
        onSecondary: { base: '#2b331e' },
        secondaryContainer: { base: '#414a33' },
        onSecondaryContainer: { base: '#dce6c7' },
        tertiary: '#a0cfca',
        onTertiary: { base: '#013734' },
        tertiaryContainer: { base: '#1f4e4a' },
        onTertiaryContainer: { base: '#bbece6' },
        error: '#ffb4a9',
        errorContainer: { base: '#930006' },
        onError: { base: '#680003' },
        onErrorContainer: { base: '#ffdad4' },
        background: { base: '#1b1c18' },
        onBackground: { base: '#e4e3dc' },
        surface: { base: '#1b1c18' },
        onSurface: { base: '#e4e3dc' },
        surfaceVariant: { base: '#44483d' },
        onSurfaceVariant: { base: '#c5c8b9' },
        outline: { base: '#8f9285' },
        inverseOnSurface: { base: '#1b1c18' },
        inverseSurface: { base: '#e4e3dc' },
      },
    },
  },
};
