// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Account: typeof import('./components/app/Account.vue')['default']
    Api: typeof import('./components/app/setting/Api.vue')['default']
    ArtistsCover: typeof import('./components/app/cover/ArtistsCover.vue')['default']
    ArtistsLink: typeof import('./components/app/artist/ArtistsLink.vue')['default']
    BFBtn: typeof import('./components/app/button/BFBtn.vue')['default']
    CardRow: typeof import('./components/app/layout/CardRow.vue')['default']
    Col: typeof import('./components/app/layout/Col.vue')['default']
    CommonCard: typeof import('./components/app/CommonCard.vue')['default']
    Cover: typeof import('./components/app/cover/Cover.vue')['default']
    Group: typeof import('./components/app/list/Group.vue')['default']
    Header: typeof import('./components/app/Header.vue')['default']
    Heading: typeof import('./components/app/Heading.vue')['default']
    Headline: typeof import('./components/app/Headline.vue')['default']
    Item: typeof import('./components/app/list/Item.vue')['default']
    List: typeof import('./components/app/list/List.vue')['default']
    LottieIcon: typeof import('./components/LottieIcon.vue')['default']
    Menu: typeof import('./components/app/menu/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/app/menu/Select.vue')['default']
    Shortcut: typeof import('./components/app/shortcuts/Shortcut.vue')['default']
    Skeleton: typeof import('./components/layout/Skeleton.vue')['default']
    SwitchCard: typeof import('./components/app/SwitchCard.vue')['default']
    Title: typeof import('./components/app/Title.vue')['default']
    TrackItem: typeof import('./components/app/TrackItem.vue')['default']
    VideoCover: typeof import('./components/app/cover/VideoCover.vue')['default']
  }
}

export {}
