// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Account: typeof import('./components/Account.vue')['default']
    ArtistsCover: typeof import('./components/cover/ArtistsCover.vue')['default']
    ArtistsLink: typeof import('./components/artist/ArtistsLink.vue')['default']
    BFBtn: typeof import('./components/button/BFBtn.vue')['default']
    CardRow: typeof import('./components/layout/CardRow.vue')['default']
    Col: typeof import('./components/layout/Col.vue')['default']
    CommonCard: typeof import('./components/CommonCard.vue')['default']
    Control: typeof import('./components/Control.vue')['default']
    ControlCenterToggle: typeof import('./components/toggle/ControlCenterToggle.vue')['default']
    Cover: typeof import('./components/cover/Cover.vue')['default']
    DiscoverLoader: typeof import('./components/skeleton/DiscoverLoader.vue')['default']
    DrawerToggle: typeof import('./components/toggle/DrawerToggle.vue')['default']
    ExploreLoader: typeof import('./components/skeleton/ExploreLoader.vue')['default']
    Heading: typeof import('./components/Heading.vue')['default']
    Headline: typeof import('./components/Headline.vue')['default']
    Item: typeof import('./components/list/Item.vue')['default']
    LikeToggle: typeof import('./components/toggle/likeToggle.vue')['default']
    List: typeof import('./components/list/List.vue')['default']
    ListLoader: typeof import('./components/skeleton/ListLoader.vue')['default']
    ListSkeleton: typeof import('./components/skeleton/ListSkeleton.vue')['default']
    LottieIcon: typeof import('./components/LottieIcon.vue')['default']
    MediaCard: typeof import('./components/MediaCard.vue')['default']
    Menu: typeof import('./components/menu/Menu.vue')['default']
    PlaylistLoader: typeof import('./components/skeleton/PlaylistSkeleton.vue')['default']
    ReloadBtn: typeof import('./components/button/ReloadBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/toggle/SearchInput.vue')['default']
    SearchToggle: typeof import('./components/toggle/SearchToggle.vue')['default']
    Select: typeof import('./components/menu/Select.vue')['default']
    SwitchCard: typeof import('./components/SwitchCard.vue')['default']
    ThemeToggle: typeof import('./components/toggle/ThemeToggle.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
    TrackItem: typeof import('./components/TrackItem.vue')['default']
    TrackList: typeof import('./components/track/TrackList.vue')['default']
    VideoCover: typeof import('./components/cover/VideoCover.vue')['default']
    WindowControl: typeof import('./components/layout/WindowControl.vue')['default']
  }
}

export {}
