name: build

on:
  push:
    branches:
      - dev
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        # env:
          # VUE_APP_API_DEV_ELECTRON: http://localhost:12138
          # VUE_APP_API_PRODUCT_ELECTRON: http://127.0.0.1:12138
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          build_script_name: 'electron:prebuild'
          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - uses: actions/upload-artifact@v3
        with:
          name: v-player-macos
          path: release/*/vplayer-next-mac*.dmg
          if-no-files-found: ignore

      - uses: actions/upload-artifact@v3
        with:
          name: v-player-windows
          path: release/*/vplayer-next*.exe
          if-no-files-found: ignore