name: dev build job

on:
  push:
    branches:
      - dev

jobs:
  mac_build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master

      - name: Setup Node.js environment
        uses: actions/setup-node@master
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci
      - run: npm run electron:build:mac
        shell: bash

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: music-you-macos
          path: release/*/music-you-mac-*-universal.dmg
          if-no-files-found: ignore

  windows_build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master

      - name: Setup Node.js environment
        uses: actions/setup-node@master
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci
      - run: npm run electron:build:win
        shell: bash

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: music-you-windows
          path: release/*/*Setup*.exe
          if-no-files-found: ignore

  linux_build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master

      - name: Setup Node.js environment
        uses: actions/setup-node@master
        with:
          node-version: 16.x
          cache: npm

      - run: npm ci
      - run: npm run electron:build:linux
        shell: bash

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: music-you-linux
          path: |
            music-you-*.AppImage
            music-you-*.tar.gz
          if-no-files-found: ignore
